# Form implementation generated from reading ui file '.\contact.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(741, 628)
        Form.setStyleSheet(
            'font: 57 10pt "Dubai Medium";\n'
            "background-color: rgb(0, 0, 63);\n"
            "color: rgb(255, 255, 255);"
        )
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 722, 161))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(parent=self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 30, 701, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nameInput = QtWidgets.QLineEdit(parent=self.widget)
        self.nameInput.setObjectName("nameInput")
        self.horizontalLayout.addWidget(self.nameInput)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.emailInput = QtWidgets.QLineEdit(parent=self.widget)
        self.emailInput.setObjectName("emailInput")
        self.horizontalLayout.addWidget(self.emailInput)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.phoneNumInput = QtWidgets.QLineEdit(parent=self.widget)
        self.phoneNumInput.setObjectName("phoneNumInput")
        self.horizontalLayout.addWidget(self.phoneNumInput)
        self.widget1 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 69, 701, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.address_input = QtWidgets.QLineEdit(parent=self.widget1)
        self.address_input.setObjectName("address_input")
        self.horizontalLayout_2.addWidget(self.address_input)
        self.widget2 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(550, 110, 158, 39))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addContactBtn = QtWidgets.QDialogButtonBox(parent=self.widget2)
        self.addContactBtn.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(0, 0, 38);\n"
            'font: 57 12pt "Dubai Medium";'
        )
        self.addContactBtn.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Reset
            | QtWidgets.QDialogButtonBox.StandardButton.Save
        )
        self.addContactBtn.setObjectName("addContactBtn")
        self.horizontalLayout_3.addWidget(self.addContactBtn)
        self.del_btn = QtWidgets.QPushButton(parent=Form)
        self.del_btn.setGeometry(QtCore.QRect(40, 590, 109, 35))
        self.del_btn.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(0, 0, 38);\n"
            'font: 57 12pt "Dubai Medium";'
        )
        self.del_btn.setObjectName("del_btn")
        self.update_btn = QtWidgets.QPushButton(parent=Form)
        self.update_btn.setGeometry(QtCore.QRect(160, 590, 113, 35))
        self.update_btn.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(0, 0, 38);\n"
            'font: 57 12pt "Dubai Medium";'
        )
        self.update_btn.setObjectName("update_btn")
        self.tabSection = QtWidgets.QTabWidget(parent=Form)
        self.tabSection.setGeometry(QtCore.QRect(10, 179, 721, 401))
        self.tabSection.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(0, 0, 38);\n"
            'font: 57 10pt "Dubai Medium";'
        )
        self.tabSection.setObjectName("tabSection")
        self.View = QtWidgets.QWidget()
        self.View.setObjectName("View")
        self.gridLayout = QtWidgets.QGridLayout(self.View)
        self.gridLayout.setObjectName("gridLayout")
        self.contactView = QtWidgets.QTableWidget(parent=self.View)
        self.contactView.setObjectName("contactView")
        self.contactView.setColumnCount(4)
        self.contactView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contactView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactView.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.contactView, 0, 0, 1, 1)
        self.tabSection.addTab(self.View, "")
        self.Search = QtWidgets.QWidget()
        self.Search.setObjectName("Search")
        self.search_contactView = QtWidgets.QTableWidget(parent=self.Search)
        self.search_contactView.setGeometry(QtCore.QRect(10, 60, 691, 291))
        self.search_contactView.setObjectName("search_contactView")
        self.search_contactView.setColumnCount(4)
        self.search_contactView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search_contactView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_contactView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_contactView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_contactView.setHorizontalHeaderItem(3, item)
        self.widget3 = QtWidgets.QWidget(parent=self.Search)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 691, 37))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=self.widget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.searchName = QtWidgets.QLineEdit(parent=self.widget3)
        self.searchName.setObjectName("searchName")
        self.horizontalLayout_4.addWidget(self.searchName)
        self.label_5 = QtWidgets.QLabel(parent=self.widget3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.searc_phoneNum = QtWidgets.QLineEdit(parent=self.widget3)
        self.searc_phoneNum.setObjectName("searc_phoneNum")
        self.horizontalLayout_4.addWidget(self.searc_phoneNum)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.search_btn = QtWidgets.QPushButton(parent=self.widget3)
        self.search_btn.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(0, 0, 38);\n"
            'font: 57 12pt "Dubai Medium"'
        )
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_5.addWidget(self.search_btn)
        self.tabSection.addTab(self.Search, "")

        self.retranslateUi(Form)
        self.tabSection.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Add Contact"))
        self.label_2.setText(_translate("Form", "Name:"))
        self.label.setText(_translate("Form", "Email:"))
        self.label_4.setText(_translate("Form", "Phone No:"))
        self.label_3.setText(_translate("Form", "Address:"))
        self.del_btn.setText(_translate("Form", "Delete Contact"))
        self.update_btn.setText(_translate("Form", "Update Contact"))
        item = self.contactView.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.contactView.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Phone No"))
        item = self.contactView.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Email"))
        item = self.contactView.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Address"))
        self.tabSection.setTabText(
            self.tabSection.indexOf(self.View), _translate("Form", "Contact View")
        )
        item = self.search_contactView.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.search_contactView.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Phone No"))
        item = self.search_contactView.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Email"))
        item = self.search_contactView.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Address"))
        self.label_6.setText(_translate("Form", "Name:"))
        self.label_5.setText(_translate("Form", "Phone No:"))
        self.search_btn.setText(_translate("Form", "Search"))
        self.tabSection.setTabText(
            self.tabSection.indexOf(self.Search), _translate("Form", "Search Contact")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
